### ISSUE TITLE
Index page (by hexo new page)

### ISSUE THREAD

**Issue by pbtrung** [zhouhao/Hexo-Tipue-Search-Json#1]
Hi,

Thank you for this useful package.
However, it can only index Hexo posts right now. Can you implement page indexing too?

Best.

**Comment by zhouhao** [comment]
Hi Trung,
Thank you for your suggestion!
You are right, better to index pages too.
I will have a try soon. ;-)

Best
Hao

**Comment by zhouhao** [comment]
<del>Will publish to npm soon</del>
Published now
