### ISSUE TITLE
Add featured image to search? 

### ISSUE THREAD

**Issue by ntot** [zhouhao/Hexo-Tipue-Search-Json#2]
Fantastic and simple plug in, thank you so much for this! :) I wanted to know if it possible to add an image to the search? Where can I edit what is displayed in the results? 

Thanks again

**Comment by zhouhao** [comment]
Thx! To edit the output search result, you can start from here https://github.com/zhouhao/hexo-Web-Source/blob/master/themes/cyanstyle/source/tipuesearch/tipuesearch.js#L372

**Comment by ntot** [comment]
Thank you, I managed to write the image path with Json but I keep getting `undefined` when I try to add the image path to the Tipue search, I am not as good with JS as you. Any suggestions?

**Comment by zhouhao** [comment]
Can I have a look of your code? I can try to help.

**Comment by ntot** [comment]
Appreciate the help, I am still learning JS :) All I want is an image next to the title, since I don't want tags I used the tags tag and replaced it with image, in my front matter I have a tag called `avatar`

The path of the image will always be the page slug so: 
 - site.com/post-1/post-1.png
 - site.com/post-2/post-2.png
 - site.com/post-3/post-3.png

[https://gist.github.com/ntot/8fd9cf73301e010be65dd07f9fb45ccc](https://gist.github.com/ntot/8fd9cf73301e010be65dd07f9fb45ccc)

I know the code is wrong but not sure how to fix. Thanks again.

**Comment by zhouhao** [comment]
Sorry to get back to you this late. Pretty busy this weekend.
BTW: could you give me a screenshot/design for how to display the image?
As I could not find any `<img>` tag in you code.

No worries, I am also learning JS now

**Comment by ntot** [comment]
Hi, thanks again, really appreciate it. Here is a sample of what I wanted to do: [https://ibb.co/bWveqk](https://ibb.co/bWveqk) All I need is to add an image next to the name, in my front matter I have a custom field called avatar and it´s also in my json file just can´t output it. Thanks again-

**Comment by zhouhao** [comment]
Sorry, I just find I have not implemented the drop-down feature. And bad news is that I cannot have  that in a short time. 🤦‍♂️

**Comment by zhouhao** [comment]
But I could have a try when I have time, but no guarantee when I will implement it

**Comment by mrttl** [comment]
HI, oh no, no drop down, it was just to show when you type a name it shows up, sorry it was my mistake, I have the search working it was just the image that I can't get working :-/

**Comment by zhouhao** [comment]
Do you mean something as this: https://twitter.github.io/typeahead.js/?

**Comment by mrttl** [comment]
Ahh yes! :) An image next to the name just like that, I don't need anything else...

**Comment by zhouhao** [comment]
Yeah, that is also what I want eventually(Not displaying result in a separate page). 
🤒 
Would have a try soon

**Comment by mrttl** [comment]
My friend no problems! You have created an amazing amazing plugin! I will use it as it is and maybe I will find out how to do it and do a PR. Thank you for your hard work and talent!

**Comment by zhouhao** [comment]
Hello @mrttl , I did some work for [hexo-theme-apollo-plus](https://github.com/zhouhao/hexo-theme-apollo-plus), and I find this ticket is better to be done with a theme. For a single plugin, it is not easy to make it compatible with most hexo themes.

I don't know what is your idea, but would like to know if you have any suggestion.
